### ISSUE TITLE
No support for alternate installation locations of minecraft.

### ISSUE THREAD

**Issue by SuperBio** [Treer/AMIDST#1]
I have my minecraft installed on another hard drive which is faster than my c drive. It would be nice if this program had a point to install directory feature.

**Comment by Treer** [comment]
Amidst has command‐line options which should do what you need, but this has never been well documented.

Run it from the command‐line with:

`-mcpath "<path to minecraft>"`

Or (if Windows) create a shortcut to AmidstExporter.exe, right‐click and select properties, then add those arguments to the end of the "Target".

For the sake of completeness, here are all the command‐line options:
- `-history` — Sets the path and file‐name to seed history file.
- `-log` — Sets the path and file‐name to the logging file.
- `-mcpath` — Sets the path to the .minecraft directory.
- `-mcjar` — Sets the path to the minecraft .jar
- `-mcjson` — Sets the path to the minecraft .json
- `-mclibs` — Sets the path to the libraries/ folder

(I should put these somewhere more prominent)
