### ISSUE TITLE
1.43 Beta Large Biomes Not Correct

### ISSUE THREAD

**Issue by jth08527** [Treer/AMIDST#2]
When using this version, the large biomes does not match what actually gets generated. The Minecraft profile version I choose is 1.8.9, and I use the same seed in that version of Minecraft. Example seed would be 2013430788579336134. Teleporting to any POI(Village, Witch Hut, etc.), they are not there. Additionally, the biomes themselves are way off. I tried several different seeds, including a few random ones, and this is always the case. I have not tried any other versions of AmidstExporter yet, but will and report back.

**Comment by jth08527** [comment]
Just tested with the last stable release 1.39, and still the same issue with large biomes. Using the seed above as an example, if you tp to 1336, 1072, AE says there is supposed to be a desert temple in a desert hills biome. But in actuality, this is open water.

**Comment by Treer** [comment]
I just tried 2013430788579336134 in Minecraft. In a newly created world which is generated using Large Biomes, the temple is there (half buried), in a Minecraft world which is generated in Default settings those coordinates takes you to open water.

So the most likely explanation is the Minecraft world you're playing in was not actually generated using Large Biomes.

Also, thanks for posting an actual seed, coordinates, and description of what's there - makes it much easier to check.

**Comment by jth08527** [comment]
You know what, I derped. Apparently this is a bug with Forge, which I forgot to mention I was using. With a Forge profile, the Large Biomes setting is not being honored. It's only generating a standard world. Sorry to bother you with this. I'll go over there and post a bug report.
