### ISSUE TITLE
Symantec up to no good

### ISSUE THREAD

**Issue by Treer** [Treer/AMIDST#3]
[Dooglin says](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262200-v3-7-amidst-strongholds-village-biome-etc-finder?comment=5097)

> @the makers of Amidst: It might be usefull to make amidst installer known to symantec.
> 
> After I downloaded it, Norton360 quarantined it because of low reputation since not many users are known.
> 
> This does not mean that it contains a virus, but just that Symantec does not know the product and is thinking that it thus is dangerous :(

so this issue is a reminder to try submitting to https://submit.symantec.com/whitelist/

Even though there is no corporation to vouch for this software.

**Comment by darthvader45** [comment]
I submitted it, and as such it appears to be safe now.
