### ISSUE TITLE
AE144.exe doesn't seem to work with Windows 10

### ISSUE THREAD

**Issue by ghost** [Treer/AMIDST#4]
I just downloaded both the .exe and .jar of version 1.4.4
and although the .jar works fine in Windows 10 the .exe does not.
The profile selection dialog doesn't even appear.

This, I believe has been true for the last several versions. Usually I only download the .exe to be able to use the AE icon it contains with the batch file I use to run the .jar.

OBTW - the reason I downloaded them is because of a forum member wanting a locations export function in Amidst and I wanted to make sure that the function still existed.
I do hope that it gets ported over to the Amidst 4.0 project.

**Comment by Treer** [comment]
Have you [unblocked](https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/) the .exe?

(The .exe works on Windows 10)

**Comment by ghost** [comment]
It turned out to be a problem with Win 10.
It works now.  I just have to make sure I right click the file and hit "Run As Administrator" or what I did was to make a shortcut on my desktop for AE144.exe and set the properties of that shortcut to run as administrator.

**Comment by Treer** [comment]
AE doesn't need to be run as Administrator on Windows 10 either.

I'm trying to imagine scenarios that could cause that... the program files directory can only be changed by Administrator, so perhaps you have AE located in the programs files directory along with a history file, and it needs to be run as admin to edit the history file?
